SELECT TO_CHAR(S.SALES_DATE,'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(S.SALES_DATE,'MM')) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U, ONLINE_SALE S
WHERE U.USER_ID = S.USER_ID AND GENDER IS NOT NULL
GROUP BY TO_CHAR(S.SALES_DATE,'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE,'MM')), U.GENDER
ORDER BY TO_CHAR(S.SALES_DATE,'YYYY'), TO_NUMBER(TO_CHAR(S.SALES_DATE,'MM')), U.GENDER
