SELECT A.AUTHOR_ID,A.AUTHOR_NAME, B.CATEGORY,SUM((S.SALES * B.PRICE)) AS TOTAL_SALES
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE B.BOOK_ID = S.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
AND TO_CHAR(S.SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY A.AUTHOR_ID, AUTHOR_NAME , B.CATEGORY
ORDER BY AUTHOR_ID , CATEGORY DESC
